version: "3"

services:

  dnsdist:
    image: tmuncks/dnsdist:latest
    restart: always
    ports:
      - 853:53/udp
      - 853:53/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dnsdist.conf:/etc/dnsdist/dnsdist.conf:ro

